### ISSUE TITLE
Swift playground

### ISSUE THREAD

**Issue by Pikachupikachup** [Hongtae/SwiftVVD#20]
Around 6 months ago, I asked if this would be available on iPad via swift playgrounds, and was responded with @Hongtae saying that there is no plans currently, but you may add it in the future. As I stated at the beginning, it has been 6 months. I wanted to get an update on where the swift playground version currently is at. Not planned, planned, started, forgot, etc. I hope/expect your quick reply!

**Comment by Hongtae** [comment]
Since the project is still in its early stages and has a lot of unimplemented parts, my schedule didn't allow me to test it properly on Swift Playground yet. I tried running the app once, but couldn't even find a way to import the github project (I had heard it was possible, but it didn't seem easy).

The project supports Mac, iOS and Mac Catalyst, so I don't think there will be any serious hardware issues, but I'm not sure about that either, as I'm not sure if Apple has allowed iPad-Playground to use 100% of the hardware's capabilities (especially Metal). 

To answer your question, I have no plans for iPad-Playground at the moment, my priority is to create an engine that works on PC, Mac, iOS and Android versions. And by iOS version I mean standalone apps (game editor, tutorial app), not a bundle that works inside Swift Playground. However, if this project becomes popular enough, I do expect a version that works on iPad Playground. 
Most game development is done on Mac and PC, so it's important to me to support those platforms first, and I hope you understand.

I apologize if this wasn't the answer you were looking for, and thank you for your interest in this project. If you have any other questions, please feel free to ask me.

**Comment by Pikachupikachup** [comment]
WAIT! I tried to insert this as a package, and all I needed was a release to open. Could you make a release, and let me try it?

**Comment by Pikachupikachup** [comment]
![image](https://github.com/Hongtae/SwiftVVD/assets/118455733/a8984797-d068-45e7-a2f1-c3de73037d3f)![image](https://github.com/Hongtae/SwiftVVD/assets/118455733/59416fa8-3bbc-4cad-8f00-9e46439b4399)
Pictures of the project in playgrounds

**Comment by Pikachupikachup** [comment]
FYI you need to put it into a swift package, instructions:
top left has a '+ file' button, click that and use the last option to open a package, and put in the BASE link of the git for it to work. It has to support swift 5.0 or later, but other than that it works!
